site_name: IBEF Backend API
site_url: https://le-riz.github.io/IBEF-Backend/
repo_url: https://github.com/Le-Riz/IBEF-Backend
repo_name: IBEF Backend

nav:
  - Home: index.md
  - Installation: installation-guide.md
  - Configuration: config.md
  - Developer Guide: dev.md
  - API Documentation:
      - API Endpoints: api.md
      - Data Models: models.md
  - API Reference: api-reference.md
  - Serial Data: serial-data.md

theme:
  name: material
  font:
    text: Red Hat Display
    code: JetBrains Mono
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy
    - palette.toggle

extra_css:
  - assets/css/custom.css
  - https://unpkg.com/katex@0/dist/katex.min.css

extra:
  generator: false

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [src]

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js
  - javascripts/katex.js
